// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package module

import (
	"github.com/google/wire"
	"gorm.io/gorm"
	"security-go/controller"
	"security-go/repository"
	"security-go/service"
)

// Injectors from auth.module.go:

// InitializeAuthModule solo para el controlador este funcionalida es exclusiva de httpServer
func InitializeAuthModule(db *gorm.DB) *controller.AuthController {
	userRolRepository := repository.NewUserRolRepository(db)
	userRolService := service.NewUserRolService(userRolRepository)
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	roleResourceRepository := repository.NewRoleResourceRepository(db)
	roleResourceService := service.NewRoleResourceService(roleResourceRepository)
	menuRepository := repository.NewMenuRepository(db)
	menuService := service.NewMenuService(menuRepository)
	resourcePermissionRepository := repository.NewResourcePermissionRepository(db)
	resourcePermissionService := service.NewResourcePermissionService(resourcePermissionRepository)
	entityRepository := repository.NewEntityRepository(db)
	entityService := service.NewEntityService(entityRepository)
	authService := service.NewAuthService(userRolService, userService, roleResourceService, menuService, resourcePermissionService, entityService)
	authController := controller.NewAuthController(authService)
	return authController
}

// InitilizeAuthService devuelve el servicio para la funcionalidad de scheduler
func InitilizeAuthService(db *gorm.DB) service.AuthService {
	userRolRepository := repository.NewUserRolRepository(db)
	userRolService := service.NewUserRolService(userRolRepository)
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	roleResourceRepository := repository.NewRoleResourceRepository(db)
	roleResourceService := service.NewRoleResourceService(roleResourceRepository)
	menuRepository := repository.NewMenuRepository(db)
	menuService := service.NewMenuService(menuRepository)
	resourcePermissionRepository := repository.NewResourcePermissionRepository(db)
	resourcePermissionService := service.NewResourcePermissionService(resourcePermissionRepository)
	entityRepository := repository.NewEntityRepository(db)
	entityService := service.NewEntityService(entityRepository)
	authService := service.NewAuthService(userRolService, userService, roleResourceService, menuService, resourcePermissionService, entityService)
	return authService
}

// Injectors from entity.module.go:

func InitializeEntityModule(db *gorm.DB) *controller.EntityController {
	entityRepository := repository.NewEntityRepository(db)
	entityService := service.NewEntityService(entityRepository)
	entityController := controller.NewEntityController(entityService)
	return entityController
}

func InitializeEntityService(db *gorm.DB) service.EntityService {
	entityRepository := repository.NewEntityRepository(db)
	entityService := service.NewEntityService(entityRepository)
	return entityService
}

// Injectors from menu.module.go:

func InitializeMenuModule(db *gorm.DB) *controller.MenuController {
	menuRepository := repository.NewMenuRepository(db)
	menuService := service.NewMenuService(menuRepository)
	menuController := controller.NewMenuController(menuService)
	return menuController
}

func InitializeMenuService(db *gorm.DB) service.MenuService {
	menuRepository := repository.NewMenuRepository(db)
	menuService := service.NewMenuService(menuRepository)
	return menuService
}

// Injectors from parameter.module.go:

func InitializeParameterModule(db *gorm.DB) *controller.ParameterController {
	parameterRepository := repository.NewParameterRepository(db)
	parameterService := service.NewParameterService(parameterRepository)
	parameterController := controller.NewParameterController(parameterService)
	return parameterController
}

func InitializeParameterService(db *gorm.DB) service.ParameterService {
	parameterRepository := repository.NewParameterRepository(db)
	parameterService := service.NewParameterService(parameterRepository)
	return parameterService
}

// Injectors from permission.module.go:

func InitializePermisoModule(db *gorm.DB) *controller.PermisoController {
	permisoRepository := repository.NewPermisoRepository(db)
	permisoService := service.NewPermisoService(permisoRepository)
	permisoController := controller.NewPermisoController(permisoService)
	return permisoController
}

func InitializePermisoService(db *gorm.DB) service.PermisoService {
	permisoRepository := repository.NewPermisoRepository(db)
	permisoService := service.NewPermisoService(permisoRepository)
	return permisoService
}

// Injectors from resource.module.go:

func InitializeResourceModule(db *gorm.DB) *controller.ResourceController {
	resourceRepository := repository.NewResourceRepository(db)
	resourceService := service.NewResourceService(resourceRepository)
	resourceController := controller.NewResourceController(resourceService)
	return resourceController
}

func InitializeResourceService(db *gorm.DB) service.ResourceService {
	resourceRepository := repository.NewResourceRepository(db)
	resourceService := service.NewResourceService(resourceRepository)
	return resourceService
}

// Injectors from resource_permission.module.go:

func InitializeResourcePermissionModule(db *gorm.DB) *controller.ResourcePermissionController {
	resourcePermissionRepository := repository.NewResourcePermissionRepository(db)
	resourcePermissionService := service.NewResourcePermissionService(resourcePermissionRepository)
	resourcePermissionController := controller.NewResourcePermissionController(resourcePermissionService)
	return resourcePermissionController
}

func InitializeResourcePermissionService(db *gorm.DB) service.ResourcePermissionService {
	resourcePermissionRepository := repository.NewResourcePermissionRepository(db)
	resourcePermissionService := service.NewResourcePermissionService(resourcePermissionRepository)
	return resourcePermissionService
}

// Injectors from rol.module.go:

func InitializeRolModule(db *gorm.DB) *controller.RolController {
	rolRepository := repository.NewRolRepository(db)
	rolService := service.NewRolService(rolRepository)
	rolController := controller.NewRolController(rolService)
	return rolController
}

func InitializeRolService(db *gorm.DB) service.RolService {
	rolRepository := repository.NewRolRepository(db)
	rolService := service.NewRolService(rolRepository)
	return rolService
}

// Injectors from role_resource.module.go:

func InitializeRoleResourceModule(db *gorm.DB) *controller.RoleResourceController {
	roleResourceRepository := repository.NewRoleResourceRepository(db)
	roleResourceService := service.NewRoleResourceService(roleResourceRepository)
	roleResourceController := controller.NewRoleResourceController(roleResourceService)
	return roleResourceController
}

func InitializeRoleResourceService(db *gorm.DB) service.RoleResourceService {
	roleResourceRepository := repository.NewRoleResourceRepository(db)
	roleResourceService := service.NewRoleResourceService(roleResourceRepository)
	return roleResourceService
}

// Injectors from trazabilidad_usuario_accion.module.go:

func InitializeTrazabilidadUsuarioAccionModule(db *gorm.DB) *controller.TrazabilidadUsuarioAccionController {
	trazabilidadUsuarioAccionRepository := repository.NewTrazabilidadUsuarioAccionRepository(db)
	trazabilidadUsuarioAccionService := service.NewTrazabilidadUsuarioAccionService(trazabilidadUsuarioAccionRepository)
	trazabilidadUsuarioAccionController := controller.NewTrazabilidadUsuarioAccionController(trazabilidadUsuarioAccionService)
	return trazabilidadUsuarioAccionController
}

func InitializeTrazabilidadUsuarioAccionService(db *gorm.DB) service.TrazabilidadUsuarioAccionService {
	trazabilidadUsuarioAccionRepository := repository.NewTrazabilidadUsuarioAccionRepository(db)
	trazabilidadUsuarioAccionService := service.NewTrazabilidadUsuarioAccionService(trazabilidadUsuarioAccionRepository)
	return trazabilidadUsuarioAccionService
}

// Injectors from user.module.go:

func InitializeUserModule(db *gorm.DB) *controller.UserController {
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userController := controller.NewUserController(userService)
	return userController
}

func InitializeUserService(db *gorm.DB) service.UserService {
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	return userService
}

// Injectors from userRol.module.go:

func InitializeUserRolModule(db *gorm.DB) *controller.UserRolController {
	userRolRepository := repository.NewUserRolRepository(db)
	userRolService := service.NewUserRolService(userRolRepository)
	userRolController := controller.NewUserRolController(userRolService)
	return userRolController
}

func InitializeUserRolService(db *gorm.DB) service.UserRolService {
	userRolRepository := repository.NewUserRolRepository(db)
	userRolService := service.NewUserRolService(userRolRepository)
	return userRolService
}

// auth.module.go:

var AuthSet = wire.NewSet(repository.NewResourcePermissionRepository, repository.NewUserRepository, repository.NewUserRolRepository, repository.NewRoleResourceRepository, repository.NewMenuRepository, repository.NewEntityRepository, service.NewResourcePermissionService, service.NewUserService, service.NewUserRolService, service.NewRoleResourceService, service.NewAuthService, service.NewMenuService, service.NewEntityService, controller.NewAuthController)

// entity.module.go:

var EntitySet = wire.NewSet(repository.NewEntityRepository, service.NewEntityService, controller.NewEntityController)

// menu.module.go:

var MenuSet = wire.NewSet(repository.NewMenuRepository, service.NewMenuService, controller.NewMenuController)

// parameter.module.go:

var parameterSet = wire.NewSet(repository.NewParameterRepository, service.NewParameterService, controller.NewParameterController)

// permission.module.go:

var PermisoSet = wire.NewSet(repository.NewPermisoRepository, service.NewPermisoService, controller.NewPermisoController)

// resource.module.go:

var ResourceSet = wire.NewSet(repository.NewResourceRepository, service.NewResourceService, controller.NewResourceController)

// resource_permission.module.go:

var resourcePermissionSet = wire.NewSet(repository.NewResourcePermissionRepository, service.NewResourcePermissionService, controller.NewResourcePermissionController)

// rol.module.go:

var RolSet = wire.NewSet(repository.NewRolRepository, service.NewRolService, controller.NewRolController)

// role_resource.module.go:

var RoleResourceSet = wire.NewSet(repository.NewRoleResourceRepository, service.NewRoleResourceService, controller.NewRoleResourceController)

// trazabilidad_usuario_accion.module.go:

var trazaSet = wire.NewSet(repository.NewTrazabilidadUsuarioAccionRepository, service.NewTrazabilidadUsuarioAccionService, controller.NewTrazabilidadUsuarioAccionController)

// user.module.go:

var UserSet = wire.NewSet(repository.NewUserRepository, service.NewUserService, controller.NewUserController)

// userRol.module.go:

var UserRoleSet = wire.NewSet(repository.NewUserRolRepository, service.NewUserRolService, controller.NewUserRolController)
