// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Soporte de API",
            "url": "http://www.soporte-api.com",
            "email": "soporte@api.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth": {
            "post": {
                "description": "Autenticacion.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "login",
                "parameters": [
                    {
                        "description": "Información de la entidad",
                        "name": "entity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AuthDTO"
                        }
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Error en el cuerpo de la solicitud",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/entity": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite actualizar la información de una entidad existente.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entidades"
                ],
                "summary": "Actualizar una entidad",
                "parameters": [
                    {
                        "description": "Información de la entidad actualizada",
                        "name": "entity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Entity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Entidad actualizada con éxito",
                        "schema": {
                            "$ref": "#/definitions/entity.Entity"
                        }
                    },
                    "400": {
                        "description": "Error en el cuerpo de la solicitud",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite crear una nueva entidad en el sistema.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entidades"
                ],
                "summary": "Crear una entidad",
                "parameters": [
                    {
                        "description": "Información de la entidad",
                        "name": "entity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Entity"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Entidad creada con éxito",
                        "schema": {
                            "$ref": "#/definitions/entity.Entity"
                        }
                    },
                    "400": {
                        "description": "Error en el cuerpo de la solicitud",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/entity/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite obtener la información de una entidad específica usando su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entidades"
                ],
                "summary": "Obtener una entidad por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la entidad",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Entidad encontrada",
                        "schema": {
                            "$ref": "#/definitions/entity.Entity"
                        }
                    },
                    "404": {
                        "description": "Entidad no encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite eliminar una entidad específica usando su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entidades"
                ],
                "summary": "Eliminar una entidad",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la entidad",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Entidad eliminada con éxito"
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/menu": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite actualizar la información de un menu existente.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "menus"
                ],
                "summary": "Actualizar un menu",
                "parameters": [
                    {
                        "description": "Información del menu actualizada",
                        "name": "resource",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Menu"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "menu actualizado con éxito",
                        "schema": {
                            "$ref": "#/definitions/entity.Menu"
                        }
                    },
                    "400": {
                        "description": "Error en el cuerpo de la solicitud",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite crear un nuevo menu en el sistema.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "menus"
                ],
                "summary": "Crear un menu",
                "parameters": [
                    {
                        "description": "Información del menu",
                        "name": "resource",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Menu"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Menu creado con éxito",
                        "schema": {
                            "$ref": "#/definitions/entity.Menu"
                        }
                    },
                    "400": {
                        "description": "Error en el cuerpo de la solicitud",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/menu/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint devuelve la información de un menu específico dado su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "menus"
                ],
                "summary": "Obtener un menu por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del menu",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "menu encontrado",
                        "schema": {
                            "$ref": "#/definitions/entity.Menu"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite eliminar un menu específico usando su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "menus"
                ],
                "summary": "Eliminar un menu",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del menu",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "menu eliminado con éxito"
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/permission": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite actualizar la información de una permiso existente.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "permisos"
                ],
                "summary": "Actualizar un permiso",
                "parameters": [
                    {
                        "description": "Información de la permisos actualizada",
                        "name": "entity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Permiso"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "permiso actualizada con éxito",
                        "schema": {
                            "$ref": "#/definitions/entity.Permiso"
                        }
                    },
                    "400": {
                        "description": "Error en el cuerpo de la solicitud",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite crear un nuevo permiso.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "permisos"
                ],
                "summary": "Crear un permiso",
                "parameters": [
                    {
                        "description": "Información de la permisos",
                        "name": "entity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Permiso"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "permiso creada con éxito",
                        "schema": {
                            "$ref": "#/definitions/entity.Permiso"
                        }
                    },
                    "400": {
                        "description": "Error en el cuerpo de la solicitud",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/permission/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite obtener la información de una permiso específica usando su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "permisos"
                ],
                "summary": "Obtener una permiso por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la permiso",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Permiso encontrada",
                        "schema": {
                            "$ref": "#/definitions/entity.Permiso"
                        }
                    },
                    "404": {
                        "description": "Permiso no encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite eliminar un permiso específica usando su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "permisos"
                ],
                "summary": "Eliminar un permiso",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la permisos",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Permisos eliminada con éxito"
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/resource_permission": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "This endpoint allows you to update a resource permission in the system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recursos-permisos"
                ],
                "summary": "Update a resource permission",
                "parameters": [
                    {
                        "description": "Updated resource permission information",
                        "name": "resource",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.ResourcePermission"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Resource permission updated successfully",
                        "schema": {
                            "$ref": "#/definitions/entity.ResourcePermission"
                        }
                    },
                    "400": {
                        "description": "Error in the request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "This endpoint allows you to create a new resource permission in the system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recursos-permisos"
                ],
                "summary": "Create a new resource permission",
                "parameters": [
                    {
                        "description": "Resource permission information",
                        "name": "resource",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.ResourcePermission"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Resource permission created successfully",
                        "schema": {
                            "$ref": "#/definitions/entity.ResourcePermission"
                        }
                    },
                    "400": {
                        "description": "Error in the request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/resource_permission/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "This endpoint returns the information of a specific resource permission given its ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recursos-permisos"
                ],
                "summary": "Get a resource permission by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Resource permission ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Resource permission found",
                        "schema": {
                            "$ref": "#/definitions/entity.ResourcePermission"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "This endpoint allows you to delete an existing resource permission in the system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recursos-permisos"
                ],
                "summary": "Delete a resource permission",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Resource permission ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Resource permission deleted successfully"
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/resources": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite actualizar la información de un recurso existente.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recursos"
                ],
                "summary": "Actualizar un recurso",
                "parameters": [
                    {
                        "description": "Información del recurso actualizada",
                        "name": "resource",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Resource"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Recurso actualizado con éxito",
                        "schema": {
                            "$ref": "#/definitions/entity.Resource"
                        }
                    },
                    "400": {
                        "description": "Error en el cuerpo de la solicitud",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite crear un nuevo recurso en el sistema.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recursos"
                ],
                "summary": "Crear un recurso",
                "parameters": [
                    {
                        "description": "Información del recurso",
                        "name": "resource",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Resource"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Recurso creado con éxito",
                        "schema": {
                            "$ref": "#/definitions/entity.Resource"
                        }
                    },
                    "400": {
                        "description": "Error en el cuerpo de la solicitud",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/resources/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite obtener la información de un recurso específico usando su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recursos"
                ],
                "summary": "Obtener un recurso por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del recurso",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Recurso encontrado",
                        "schema": {
                            "$ref": "#/definitions/entity.Resource"
                        }
                    },
                    "404": {
                        "description": "Recurso no encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite eliminar un recurso específico usando su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recursos"
                ],
                "summary": "Eliminar un recurso",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del recurso",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Recurso eliminado con éxito"
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rol": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite actualizar la información de un Rol existente.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rols"
                ],
                "summary": "Actualizar un Rol",
                "parameters": [
                    {
                        "description": "Información del Rol actualizada",
                        "name": "resource",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Rol"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Rol actualizado con éxito",
                        "schema": {
                            "$ref": "#/definitions/entity.Rol"
                        }
                    },
                    "400": {
                        "description": "Error en el cuerpo de la solicitud",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite crear un nuevo Rol en el sistema.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rols"
                ],
                "summary": "Crear un Rol",
                "parameters": [
                    {
                        "description": "Información del Rol",
                        "name": "resource",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Rol"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Rol creado con éxito",
                        "schema": {
                            "$ref": "#/definitions/entity.Rol"
                        }
                    },
                    "400": {
                        "description": "Error en el cuerpo de la solicitud",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rol-recurso": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite actualizar la información de un rol recurso existente.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roles-recursos"
                ],
                "summary": "Actualizar un rol recurso",
                "parameters": [
                    {
                        "description": "Información del rol recurso actualizada",
                        "name": "resource",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.RoleResource"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "rol recurso actualizado con éxito",
                        "schema": {
                            "$ref": "#/definitions/entity.RoleResource"
                        }
                    },
                    "400": {
                        "description": "Error en el cuerpo de la solicitud",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rol-recurso/asignar": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite crear un nuevo rol recurso en el sistema.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roles-recursos"
                ],
                "summary": "Crear un rol recurso",
                "parameters": [
                    {
                        "description": "Información del rol recurso",
                        "name": "resource",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.RoleResource"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Rol recurso creado con éxito",
                        "schema": {
                            "$ref": "#/definitions/entity.RoleResource"
                        }
                    },
                    "400": {
                        "description": "Error en el cuerpo de la solicitud",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rol-recurso/desasignar/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite eliminar un rol recurso existente en el sistema.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roles-recursos"
                ],
                "summary": "Eliminar un rol recurso",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del rol recurso",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Rol recurso eliminado con éxito",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rol-recurso/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint devuelve la información de un rol recurso específico dado su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roles-recursos"
                ],
                "summary": "Obtener un rol recurso por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del rol recurso",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "rol recurso encontrado",
                        "schema": {
                            "$ref": "#/definitions/entity.RoleResource"
                        }
                    }
                }
            }
        },
        "/rol/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint devuelve la información de un Rol específico dado su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rols"
                ],
                "summary": "Obtener un Rol por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Rol",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Rol encontrado",
                        "schema": {
                            "$ref": "#/definitions/entity.Rol"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite eliminar un Rol específico usando su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rols"
                ],
                "summary": "Eliminar un Rol",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Rol",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Rol eliminado con éxito"
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite actualizar la información de un usuario existente.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "usuarios"
                ],
                "summary": "Actualizar un usuario",
                "parameters": [
                    {
                        "description": "Información del usuario",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Usuario actualizado",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite crear un nuevo usuario en el sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "usuarios"
                ],
                "parameters": [
                    {
                        "description": "Información del usuario",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    }
                }
            }
        },
        "/user-rol/asignar": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite crear un nueva relacion usuarioRol en el sistema.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "re-usuario-rol"
                ],
                "summary": "Crear un recurso",
                "parameters": [
                    {
                        "description": "Información del recurso",
                        "name": "UserRol",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.UserRol"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Recurso creado con éxito",
                        "schema": {
                            "$ref": "#/definitions/entity.UserRol"
                        }
                    },
                    "400": {
                        "description": "Error en el cuerpo de la solicitud",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user-rol/desasignar/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite eliminar una relacion usuario rol específico usando su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "re-usuario-rol"
                ],
                "summary": "Eliminar una relacion usuario rol",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del usuario rol",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "usuario rol eliminado con éxito"
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint devuelve la información de un usuario específico dado su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "usuarios"
                ],
                "summary": "Obtener un usuario por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del usuario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Usuario encontrado",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Este endpoint permite eliminar un usuario específico dado su ID.",
                "tags": [
                    "usuarios"
                ],
                "summary": "Eliminar un usuario por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del usuario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Usuario eliminado con éxito"
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AuthDTO": {
            "type": "object",
            "properties": {
                "contraseña": {
                    "type": "string"
                },
                "usuario": {
                    "type": "integer"
                }
            }
        },
        "entity.Entity": {
            "type": "object",
            "properties": {
                "activo": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "entidad_id": {
                    "type": "integer"
                },
                "nit": {
                    "type": "integer"
                },
                "nit_alterno": {
                    "type": "string"
                },
                "razon_social": {
                    "type": "string"
                }
            }
        },
        "entity.Menu": {
            "type": "object",
            "properties": {
                "descripcion": {
                    "type": "string"
                },
                "entidad": {
                    "$ref": "#/definitions/entity.Entity"
                },
                "entidad_id": {
                    "type": "integer"
                },
                "menuID": {
                    "type": "integer"
                },
                "menu_padre": {
                    "$ref": "#/definitions/entity.Menu"
                },
                "menu_padre_id": {
                    "type": "integer"
                },
                "nombre": {
                    "type": "string"
                },
                "recurso": {
                    "$ref": "#/definitions/entity.Resource"
                },
                "recurso_id": {
                    "type": "integer"
                }
            }
        },
        "entity.Permiso": {
            "type": "object",
            "properties": {
                "accion": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                },
                "permiso_id": {
                    "type": "integer"
                }
            }
        },
        "entity.Resource": {
            "type": "object",
            "properties": {
                "acceso": {
                    "type": "string"
                },
                "descripcion": {
                    "type": "string"
                },
                "recurso_id": {
                    "type": "integer"
                }
            }
        },
        "entity.ResourcePermission": {
            "type": "object",
            "properties": {
                "permiso": {
                    "$ref": "#/definitions/entity.Permiso"
                },
                "permiso_id": {
                    "type": "integer"
                },
                "recurso": {
                    "$ref": "#/definitions/entity.Resource"
                },
                "recursoPermisoID": {
                    "type": "integer"
                },
                "recurso_id": {
                    "type": "integer"
                },
                "rol": {
                    "$ref": "#/definitions/entity.Rol"
                },
                "rol_id": {
                    "type": "integer"
                }
            }
        },
        "entity.Rol": {
            "type": "object",
            "properties": {
                "activo": {
                    "type": "boolean"
                },
                "descripcion": {
                    "type": "string"
                },
                "entidad_id": {
                    "type": "integer"
                },
                "nombre": {
                    "type": "string"
                },
                "rolID": {
                    "type": "integer"
                }
            }
        },
        "entity.RoleResource": {
            "type": "object",
            "properties": {
                "acceso": {
                    "type": "string"
                },
                "entidad": {
                    "$ref": "#/definitions/entity.Entity"
                },
                "entidad_id": {
                    "type": "integer"
                },
                "recurso": {
                    "$ref": "#/definitions/entity.Resource"
                },
                "recurso_id": {
                    "type": "integer"
                },
                "rol": {
                    "$ref": "#/definitions/entity.Rol"
                },
                "rolRecursoID": {
                    "type": "integer"
                },
                "rol_id": {
                    "type": "integer"
                }
            }
        },
        "entity.User": {
            "type": "object",
            "properties": {
                "activo": {
                    "type": "boolean"
                },
                "apellido_materno": {
                    "type": "string"
                },
                "apellido_paterno": {
                    "type": "string"
                },
                "cambiar_clave": {
                    "type": "boolean"
                },
                "clave": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fecha_cambio_clave": {
                    "type": "string"
                },
                "fecha_creacion": {
                    "type": "string"
                },
                "fecha_retiro": {
                    "type": "string"
                },
                "nombre_1": {
                    "type": "string"
                },
                "nombre_2": {
                    "type": "string"
                },
                "tiempo_valides_token": {
                    "type": "string"
                },
                "usuario": {
                    "type": "integer"
                },
                "usuario_id": {
                    "type": "integer"
                }
            }
        },
        "entity.UserRol": {
            "type": "object",
            "properties": {
                "entidad_id": {
                    "type": "integer"
                },
                "fecha_fin": {
                    "type": "string"
                },
                "fecha_inicio": {
                    "type": "string"
                },
                "indefinido": {
                    "type": "boolean"
                },
                "rol_id": {
                    "type": "integer"
                },
                "usuarioRolID": {
                    "type": "integer"
                },
                "usuario_id": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Ingresa \"Bearer {token}\" para autenticar.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9000",
	BasePath:         "/medfri-security",
	Schemes:          []string{},
	Title:            "medfri-security",
	Description:      "micro de seguridad.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
